language: python
cache: pip

python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  # install blender from official sources.
  # This will most propably install an outdated blender version,
  # but it will resolve all system dependencies blender has to be able to run.
  - sudo apt-get install blender
  - pip install requests
  - pip install StringIO
  - pip install wget

install:
  - mkdir tmp && cd tmp
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender2.74/blender-2.74-linux-glibc211-x86_64.tar.bz2
  - tar jxf blender-2.74-linux-glibc211-x86_64.tar.bz2
  - mv blender-2.74-linux-glibc211-x86_64 blender
  - rm blender-2.74-linux-glibc211-x86_64.tar.bz2

  - cd ..

  # Make sure to install mmd_tools plugin
  - python downloadmmd_tools.py
  - sudo ln -s ${PWD}/tmp/mmd_tools/blender_mmd_tools-dev_test/mmd_tools ${PWD}/tmp/blender/2.74/scripts/addons/mmd_tools

  # make sure to install cats plugin
  - sudo ln -s ${PWD} ${PWD}/tmp/blender/2.74/scripts/addons/cats

# Finally start our test runner passing it the blender executable from the downloaded blender release
script: python tests.py ./tmp/blender/blender
